struct_lit_width = 60
max_width = 120
chain_width = 80
fn_single_line = true
short_loop_body_width = 80
inline_attribute_width = 80
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
enum_discrim_align_threshold = 80
struct_field_align_threshold = 80
